// <auto-generated />
using System;
using EF_CodeFirst.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_CodeFirst.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20220330193224_DBSeed")]
    partial class DBSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EF_CodeFirst.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"), 1L, 1);

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("GradeId");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            GradeId = 1,
                            GradeName = "Essay",
                            Section = "",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 2,
                            GradeName = "Vocabulary",
                            Section = "",
                            StudentId = 2
                        },
                        new
                        {
                            GradeId = 3,
                            GradeName = "Grammar",
                            Section = "",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 4,
                            GradeName = "Homework",
                            Section = "",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 5,
                            GradeName = "Project",
                            Section = "",
                            StudentId = 2
                        },
                        new
                        {
                            GradeId = 6,
                            GradeName = "Quiz",
                            Section = "",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 7,
                            GradeName = "Test",
                            Section = "",
                            StudentId = 2
                        });
                });

            modelBuilder.Entity("EF_CodeFirst.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NCHAR(50)");

                    b.Property<double?>("Weight")
                        .HasColumnType("FLOAT");

                    b.HasKey("StudentID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            DateOfBirth = new DateTime(2022, 3, 30, 21, 32, 24, 653, DateTimeKind.Local).AddTicks(7437),
                            Height = 1.80m,
                            StudentName = "Marky Mark",
                            Weight = 79.0
                        },
                        new
                        {
                            StudentID = 2,
                            DateOfBirth = new DateTime(2022, 3, 30, 21, 32, 24, 653, DateTimeKind.Local).AddTicks(7480),
                            Height = 1.68m,
                            StudentName = "Barbie Rossberg",
                            Weight = 66.0
                        });
                });

            modelBuilder.Entity("EF_CodeFirst.Models.Grade", b =>
                {
                    b.HasOne("EF_CodeFirst.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
